### ISSUE TITLE
recast module not found

### ISSUE THREAD

**Issue by bradparks** [nolanlawson/cjs-to-es6#1]
Hey! to get this to work, I had to 

`npm install -g recast` as the module wasn't found

Thanks! This was a total time saver!

**Comment by bradparks** [comment]
and for what it's worth, I noticed that a bunch of "var" declarations were left as they were, in the following snippet:
```

// MultiSelect = require("react-selectize").MultiSelect

Form = React.createClass({
    
    // render :: a -> ReactElement
    render: function(){
        var self = this, 
            fruits = ["apple", "mango", "grapes", "melon", "strawberry", "cherry", "banana", "kiwi"],
            options = fruits.map(function(fruit){
                return {label: fruit, value: fruit}
            });
        return <div style = {{border: '1px solid black', height: 100, overflow: "auto", padding: 20}}>

            <div style = {{padding: 20}}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit
            </div>

            <MultiSelect tether = {true} options = {options} placeholder = "Select fruits"></MultiSelect>

            <div style = {{padding: 20}}>
                Fusce aliquet dui tortor, imperdiet viverra augue pretium nec
            </div>

        </div>
    }
    
});

render(<Form/>, mountNode)
```

**Comment by nolanlawson** [comment]
Yeah, this module isn't perfect, and it mostly just wraps other libs. I wasn't aware of the `'recast'` issue - works on my machine without modifications! (OS X, Node 5). PRs welcome. :)

**Comment by lshearer** [comment]
I had the same issue with `recast`, and doing `npm i -g recast` led to another error. Looks like the problem is with missing runtime dependencies in `5to6-codemod` ([fixed, but not published](https://github.com/5to6/5to6-codemod/pull/15)) when using npm 2.x. npm 3.x apparently masks the problem when flattening the dependency tree because it pulls `recast` out of `jscodeshift` to the top-level `node_modules` directory.

**Comment by nolanlawson** [comment]
closing old issues, please reopen as necessary
